# Generated by Django 2.2.26 on 2022-02-08 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='bt_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='bt_host_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('associated', models.CharField(max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='dns_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('dns', models.CharField(max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='dns_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('SecretId', models.CharField(max_length=50)),
                ('SecretKey', models.CharField(max_length=50)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='dns_save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('dns_zhi', models.CharField(max_length=32)),
                ('dns', models.CharField(max_length=32)),
                ('dns_jie', models.CharField(max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
                ('endtime', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Kangle_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=32)),
                ('server_name', models.CharField(max_length=32)),
                ('server_pwd', models.CharField(max_length=32)),
                ('server_key', models.CharField(max_length=32)),
                ('server_type', models.CharField(max_length=32)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.CharField(max_length=32)),
                ('sever_state', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User_zhuce3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('pw', models.CharField(max_length=32)),
                ('yue', models.CharField(max_length=32)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
